apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploynemt
  labels:
    name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app
    spec:
      containers:
        - name: redis-app
          image: artifactory.otxlab.net/dockerhub/redis





